- name: check if user exists
  getent:
    database: passwd
    key: "{{ admin_user_name }}"
  ignore_errors: true
  register: user_check

- block: 
    - name: install sudo
      package:
        name: sudo
        state: present

    - name: allow user to have passwordless sudo
      copy:
        content: '{{ admin_user_name }} ALL=(ALL) NOPASSWD: ALL'
        dest: /etc/sudoers.d/{{ admin_user_name }}_nopasswd
        mode: 0440

    - name: create admin user with sudo privileges
      user:
        name: "{{ admin_user_name }}"
        groups: >
          {% if ansible_os_family == 'Debian' %}
          sudo
          {% elif ansible_os_family == 'RedHat' %}
          wheel
          {% else %}
          {% endif %}
        append: true
        create_home: true
        shell: /bin/bash
        state: present

    - name: set authorized key for remote user
      authorized_key:
        user: "{{ admin_user_name }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  when: user_check.failed
