- name: enable ip forward for access to local network
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    reload: yes
    state: present  
  become: yes

# https://github.com/Nyr/wireguard-install
- name: downloading wireguard installer to home directory
  get_url:
    url: https://git.io/wireguard
    dest: /home/ansible/wireguard-install.sh
