- name: enable ip-forward for access to local network
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    reload: true
    state: present
  become: true

# https://github.com/Nyr/wireguard-install
- name: downloading wireguard installer to home directory
  get_url:
    url: https://git.io/wireguard
    dest: /home/ansible/wireguard-install.sh
    mode: 0644
