- name: Copy compose file
  ansible.builtin.copy:
    src: compose-files/{{ current_project }}/
    dest: "{{ compose_container_dir }}/{{ current_project }}"
    force: true

- name: Pull images
  community.docker.docker_compose_v2_pull:
    project_src: "{{ compose_container_dir }}/{{ current_project }}"
  environment:
    DOCKER_APP_DATA: "{{ compose_app_data_dir }}"

- name: Start services definded in the docker compose file
  community.docker.docker_compose_v2:
    project_src: "{{ compose_container_dir }}/{{ current_project }}"
    state: present
  environment:
    DOCKER_APP_DATA: "{{ compose_app_data_dir }}"

- name: Prune unused Docker images and containers
  ansible.builtin.command: docker system prune -af
  register: prune_output
  ignore_errors: true
  changed_when: '"deleted" in result.stdout'

- name: Display prune output
  ansible.builtin.debug:
    var: prune_output.stdout_lines
