---
- name: Check (or create) app-data directory
  ansible.builtin.file:
    path: "{{ compose_app_data_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
  become: true

- name: Add DOCKER_APP_DATA env to .profile
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: "export DOCKER_APP_DATA='{{ compose_app_data_dir }}'"
    state: present

- name: Find existing docker-compose directories
  ansible.builtin.find:
    paths: "{{ compose_container_dir }}"
    patterns: docker-compose.yml
    recurse: true
  register: existing_compose

- name: Run docker-compose down on each directory
  community.docker.docker_compose_v2:
    project_src: "{{ item.path | dirname }}"
    state: absent
  loop: "{{ existing_compose.files }}"
  environment:
    DOCKER_APP_DATA: "{{ compose_app_data_dir }}"

- name: Delete existing docker-compose directories
  ansible.builtin.file:
    path: "{{ item.path | dirname }}"
    state: absent
  loop: "{{ existing_compose.files }}"

- name: Include tasks for each compose project
  ansible.builtin.include_tasks: compose_project.yml
  loop: "{{ compose_projects }}"
  loop_control:
    loop_var: current_project
