- name: check if user exists
  getent:
    database: passwd
    key: "{{ admin_user }}"
  ignore_errors: true

- block: 
    - name: install sudo
      package:
        name: sudo
        state: present

    - name: create admin user with sudo privileges
      user:
        name: "{{ admin_user }}"
        groups: >
          {% if ansible_os_family == 'Debian' %}
          sudo
          {% elif ansible_os_family == 'RedHat' %}
          wheel
          {% else %}
          {% endif %}
        append: true
        create_home: true
        shell: /bin/bash
        state: present

    - name: set authorized key for remote user
      authorized_key:
        user: "{{ admin_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  become: true
