memory: 1024
swap: 256
onboot: 1
cores: 1
pct_create_command: >
  pct create {{ container_id }}
  /var/lib/vz/template/cache/{{ container_template }}
  -arch amd64
  -cores {{ cores }}
  -hostname {{ container_hostname }}
  -memory {{ memory }}
  -net0 "name=eth0,bridge=vmbr0,gw=192.168.1.1,ip={{ container_ip }}/24"
  -onboot {{ onboot }}
  -ostype debian
  -password {{ lookup('ansible.builtin.password', '/tmp/root_password', length=10) }}
  -ssh-public-keys /root/.ssh/authorized_keys
  -start 1
  -storage local-lvm
  -swap {{ swap }}
  -unprivileged 1
