- name: check if admin user [{{ admin_user }}] exists
  ansible.builtin.getent:
    database: passwd
    key: "{{ admin_user }}"
  ignore_errors: true
  register: result

- block: 
    - name: install sudo
      ansible.builtin.package:
        name: sudo
        state: present

    - name: create new user [{{ admin_user }}] with sudo group
      ansible.builtin.user:
        name: "{{ admin_user }}"
        groups: >
          {% if ansible_os_family == 'Debian' %}
          sudo
          {% elif ansible_os_family == 'RedHat' %}
          wheel
          {% else %}
          {% endif %}
        append: true
        create_home: true
        shell: /bin/bash
        state: present

    - name: Allow passwordless sudo for specific group
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set ssh authorized key for new user
      ansible.builtin.authorized_key:
        user: "{{ admin_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  when: result is failed
