- name: check for .dotfiles directory
  file:
    path: ~/.dotfiles/
    state: directory
  register: dot_result

- name: install dotfiles
  block:
    - name: remove original .bashrc file
      file:
        path: ~/.bashrc
        state: absent

    - name: Make config directory
      file:
        path: ~/.config
        state: directory
  when: dot_result.changed == true

- name: clone dotfile repo
  git:
    repo: "{{ dotfile_repo }}"
    dest: ~/.dotfiles/
    clone: yes
    update: yes
    version: main

- name: (re)stow dotfiles for bash neovim update-dotfiles
  command:
    cmd: stow -R --no-folding bash neovim update-dotfiles
    chdir: ~/.dotfiles/

- name: force systemd to reread configs
  systemd:
    scope: user
    daemon_reload: true

- name: enable update-dotfiles systemd timer
  systemd:
    name: update-dotfiles.timer
    scope: user
    enabled: true 
    state: started
