# https://github.com/junegunn/vim-plug
- name: "create neovim autoload directory"
  file: path="~/.config/nvim/autoload" state=directory

- name: "download vim-plug autoload"
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim

- name: "neovim PlugUpdate (PlugInstall || PlugUpgrade)"
  command: nvim "+silent! PlugUpdate!" +qall!
