- name: Check For Dotfiles Directory
  ansible.builtin.file:
    path: ~/.dotfiles/
    state: directory
    mode: '0755'
  register: dot_result

- name: Prepare for Dotfiles Installation
  when: dot_result.changed
  block:
    - name: Backup Original Bash Config Files
      ansible.builtin.command: mv {{ item }} {{ item }}.orig
      loop:
        - "~/.bash_aliases"
        - "~/.bashrc"
        - "~/.profile"
      ignore_errors: true

    - name: Create Config Directory
      ansible.builtin.file:
        path: ~/.config
        state: directory
        mode: '0755'

- name: Clone Dotfile Git Repo
  ansible.builtin.git:
    repo: "{{ dotfile_repo }}"
    dest: ~/.dotfiles/
    clone: true
    update: true
    version: main
  notify:
    - Stow Dotfiles
