- name: check for .dotfiles directory
  file:
    path: ~/.dotfiles/
    state: directory
  register: dot_result

- name: install dotfiles
  block:
    - name: clone dotfile repo
      git:
        repo: "{{ dotfile_repo }}"
        dest: ~/.dotfiles/
        clone: yes
        version: main

    - name: remove original .bashrc file
      file:
        path: ~/.bashrc
        state: absent

    - name: Make config directory
      file:
        path: ~/.config
        state: directory

    - name: stow dotfiles for bash, neovim, and the update script.
      command:
        cmd: stow bash neovim update-dotfiles
        chdir: ~/.dotfiles/
  when: dot_result.changed == true

- name: restow dotfiles incase of changes
  command:
    cmd: stow -R bash neovim update-dotfiles
    chdir: ~/.dotfiles/
  when: dot_result.changed == false

- name: force systemd to reread configs
  systemd:
    scope: user
    daemon_reload: true

- name: enable update-dotfiles systemd timer
  systemd:
    name: update-dotfiles.timer
    scope: user
    enabled: true 
    state: started
