# Install vim-plug
- block:
  - name: create neovim autoload directory
    file: path="~/.config/nvim/autoload" state=directory

  - name: Install vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: ~/.config/nvim/autoload/plug.vim
      force: yes

- block:
  - name: Install vim plugins
    command: nvim "+silent! PlugInstall!" +qall!
