- name: install epel repo
  yum:
    name:
      - epel-release
    state: present
    update_cache: true
  become: true

- name: add alternative private neofetch repo
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/konimex/neofetch/repo/epel-7/konimex-neofetch-epel-7.repo
    dest: /etc/yum.repos.d/konimex-neofetch-epel-7.repo
    mode: 0644
  become: true

- name: 'install system packages'
  yum:
    name: "{{ sys_packages }}"
    state: present
    update_cache: true
  become: true

- include_tasks: install-dot-files.yml
- include_tasks: install-vim-plugins.yml
