- include_tasks: set-timezone.yml

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  become: yes

- name: install epel repo
  yum:
    name:
      - epel-release
    state: present
    update_cache: yes
  become: yes

- name: add alternative private neofetch repo
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/konimex/neofetch/repo/epel-7/konimex-neofetch-epel-7.repo
    dest: /etc/yum.repos.d/konimex-neofetch-epel-7.repo
    force: yes
  become: yes

- name: 'install system packages'
  yum:
    name: "{{ sys_packages }}"
    state: present
    update_cache: yes
  become: yes

- include_tasks: install-dot-files.yml 
- include_tasks: install-vim-plugins.yml
