- name: Check whether container exists
  shell: "lxc-ls -f | grep -e {{ container_id }} -e {{ container_ip }}"
  changed_when: false
  ignore_errors: true
  register: lxc_list

- name: create new lxc container
  command: >
    pct create {{ container_id }}
    /var/lib/vz/template/cache/{{ container_template }}
    -arch amd64
    -ostype debian
    -hostname {{ container_hostname }}
    -cores 1
    -memory 512
    -swap 128
    -storage local-lvm
    -net0 "name=eth0,bridge=vmbr0,gw=192.168.1.1,ip={{ container_ip }}/24"
    -ssh-public-keys /root/.ssh/authorized_keys
    -unprivileged 1
    -start 1
  when: lxc_list.rc != 0
