- name: clone container repo
  git:
    repo: "{{ container_repo }}"
    dest: ~/docker-containers/
    clone: true
    update: true
    version: main

- name: check (or create) app-data directory
  file:
    path: "{{ app_data_dir }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true

- name: add DOCKER_APP_DATA env to .profile
  lineinfile:
    path: ~/.profile
    line: "export DOCKER_APP_DATA='{{ app_data_dir }}'"
    state: present
  ignore_errors: true

- name: add DOCKER_APP_DATA env to .bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: "export DOCKER_APP_DATA='{{ app_data_dir }}'"
    state: present
  ignore_errors: true
