- name: Restart SSHD
  ansible.builtin.systemd:
    name: sshd
    enabled: true
    state: restarted

- name: SSHD Config Change Reminder
  ansible.builtin.debug:
    msg:  "SSHD config changed. Reminder to change SSH config on localhost"

- import_tasks: handlers/nftables.yml
- import_tasks: handlers/iptables.yml
