- name: Create backup of sshd_config
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.orig
    mode: 0644
    remote_src: true
    force: false

- name: Change SSH port
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?Port'
    line: "Port {{ hvps_ssh_port }}"
  notify: Restart SSHD

- name: Disable password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
  notify: Restart SSHD

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PasswordAutnetication'
    line: 'PasswordAuthentication no'
  notify: Restart SSHD
